services:
  - type: worker
    name: GiftBuyerBot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app/main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
